# File cấu hình wrangler.toml cho dự án Cloudflare Pages
# Phiên bản này đã loại bỏ trường "name" để tương thích tốt hơn.

compatibility_date = "2024-06-17"

# Chỉ cho Cloudflare biết thư mục chứa frontend (HTML, CSS...)
pages_build_output_dir = "public"

# Bật chế độ tương thích Node.js cho tất cả các functions của project này.
# Đây là cờ quan trọng nhất để sửa lỗi "Could not resolve".
node_compat = true

# Khai báo binding D1 ở cấp cao nhất.
# Cloudflare Pages sẽ tự động liên kết nó với Functions của bạn.
[[d1_databases]]
binding = "DB" # Tên binding phải khớp với code: env.DB
database_name = "mwang-db-app"
database_id = "fbcfd28a-9b89-419b-8baa-b27f3f14926f"